package com.example.demo.utils;

import java.security.SecureRandom;
import java.util.UUID;

import org.springframework.context.annotation.Lazy;
import org.springframework.stereotype.Service;
import org.springframework.util.IdGenerator;

/**
 * Encapsulate various tools for generating unique ID algorithms.
 */
@Service
@Lazy(false)
public class IdGen implements IdGenerator {

    private static SecureRandom random = new SecureRandom();

    /**
     * Encapsulate the UUID that comes with JDK, generated by Random numbers, without split.
     */
    public static String uuid() {
        return UUID.randomUUID().toString().replaceAll("-", "");
    }

    /**
     * Randomly generate Long using SecureRandom.
     */
    public static long randomLong() {
        return Math.abs(random.nextLong());
    }

    /**
     * Activiti ID generation
     */
    public String getNextId() {
        return IdGen.uuid();
    }

    @Override
    public UUID generateId() {
        // TODO Auto-generated method stub
        return null;
    }

}

